apiVersion: v1
kind: ConfigMap
metadata:
  name: app-two
data:
  index.html: |
    <html>
      <body style="font-family: sans-serif; text-align:center; margin-top: 10%;">
        <h1>Hello from app2</h1>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
  labels:
    app: two
spec:
  replicas: 3
  selector:
    matchLabels:
      app: two
  template:
    metadata:
      labels:
        app: two
    spec:
      containers:
        - name: app-two
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: app-two
---
apiVersion: v1
kind: Service
metadata:
  name: app-two
spec:
  type: ClusterIP
  selector:
    app: two
  ports:
    - protocol: TCP
      targetPort: 80
      port: 8082 
