# Variables
LOGIN = "akurochk"
OS = "debian/trixie64"
NETWORK_NAME = "private_network"
PROVIDER = "libvirt"
SERVER_IP = "192.168.56.110"
SCRIPT_SERVER = "./scripts/server.sh"

Vagrant.configure("2") do |config|

    # Common settings
    config.vm.box = "#{OS}"
    config.vm.box_check_update = false
    config.vm.provider "#{PROVIDER}" do |vm|
        vm.memory = "2048"
        vm.cpus = "1"
    end

    # Server (control-plane)
    config.vm.define "#{LOGIN}S" do |server|
        server.vm.hostname = "#{LOGIN}S"
        server.vm.network "#{NETWORK_NAME}", ip: "#{SERVER_IP}"
        server.vm.provision "shell", path: "#{SCRIPT_SERVER}"
    end

end
