# Variables
OS      = "debian/trixie64"
LOGIN   = {server: "akurochkS", worker: "akurochkSW"}
NETWORK = {server: "192.168.56.110", worker: "192.168.56.111"}
SCRIPT  = {server: "./scripts/server.sh", worker: "./scripts/worker.sh"}

Vagrant.configure("2") do |config|

    # Common settings
    config.vm.box = OS
    config.vm.box_check_update = false
    config.vm.synced_folder ".", "/vagrant"
    config.vm.provider "libvirt" do |vm|
        vm.memory = 2048
        vm.cpus = 1
    end

    # Server (control-plane)
    config.vm.define LOGIN[:server] do |server|
        server.vm.hostname = LOGIN[:server]
        server.vm.network "private_network", ip: NETWORK[:server]
        server.vm.provision "shell", path: SCRIPT[:server]
    end

    # Worker (agent)
    config.vm.define LOGIN[:worker] do |worker|
        worker.vm.hostname = LOGIN[:worker]
        worker.vm.network "private_network", ip: NETWORK[:worker]
        worker.vm.provision "shell", path: SCRIPT[:worker]
    end

end
